export { Navbar } from './navbar';
export { Hero } from './hero';
export { PartnersBanner } from './partners-banner';
export { HowItWorks } from './how-it-works';
export * from './navbar';
export * from './footer';
export * from './hero';
export * from './how-it-works';
export * from './featured-products';
export * from './testimonials';
export * from './become-designer';
export * from './partners-banner';
export * from './chatbot';
